// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.TestingThing2;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController subsystem1LeftFront;
    public static SpeedController subsystem1RightFront;
    public static SpeedController subsystem1LeftBack;
    public static SpeedController subsystem1RightBack;
    public static RobotDrive subsystem1RobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        subsystem1LeftFront = new Talon(0);
        LiveWindow.addActuator("Subsystem 1", "Left Front", (Talon) subsystem1LeftFront);
        
        subsystem1RightFront = new Talon(1);
        LiveWindow.addActuator("Subsystem 1", "Right Front", (Talon) subsystem1RightFront);
        
        subsystem1LeftBack = new Talon(2);
        LiveWindow.addActuator("Subsystem 1", "Left Back", (Talon) subsystem1LeftBack);
        
        subsystem1RightBack = new Talon(3);
        LiveWindow.addActuator("Subsystem 1", "Right Back", (Talon) subsystem1RightBack);
        
        subsystem1RobotDrive41 = new RobotDrive(subsystem1LeftFront, subsystem1LeftBack,
              subsystem1RightFront, subsystem1RightBack);
        
        subsystem1RobotDrive41.setSafetyEnabled(true);
        subsystem1RobotDrive41.setExpiration(0.1);
        subsystem1RobotDrive41.setSensitivity(0.5);
        subsystem1RobotDrive41.setMaxOutput(1.0);

        subsystem1RobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        subsystem1RobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
